# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Node.js Package

on:
  pull_request:
    branches: [ master ]
    types:
      - closed
jobs:
  publish:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: manifest 🏗️
        run: npx @kne/md-index
      - uses: kne-union/actions-deploy-static-data@master
        with:
          token: ${{ secrets.ADMIN_TOKEN }}
          name: engineering
